URL_SERVICE = "https://0eba1d38-75ca-4e40-a8c8-157ff1d688df.serverhub.praktikum-services.ru"
DOC_PATH = "/docs/"
LOG_PATH = "/api/logs/main/"
USER_MODEL_PATH = "/api/db/resources/orders.csv"
CREATE_USER_PATH = "/api/v1/users/"
CREATE_ORDER_PATH = "/api/v1/orders"
GET_ORDER_BY_TRACK_PATH = "/api/v1/orders/track"
