URL_SERVICE = "https://c1cc7616-a36b-4c6c-a6d5-9d5ac2f0e09f.serverhub.praktikum-services.ru"
DOC_PATH = "/docs/"
LOG_PATH = "/api/logs/main/"
USER_MODEL_PATH = "/api/db/resources/user_model.csv"
CREATE_USER_PATH = "/api/v1/users/"
PRODUCTS_KITS_PATH = "/api/v1/products/kits/"