URL_SERVICE = "https://85f27934-66d2-4f87-b6d0-a68f892f9a56.serverhub.praktikum-services.ru"
DOC_PATH = "/docs/"
LOG_PATH = "/api/logs/main/"
USER_MODEL_PATH = "/api/db/resources/user_model.csv"
CREATE_USER_PATH = "/api/v1/users/"
CREATE_ORDER_PATH = "/api/v1/orders"
GET_ORDER_BY_TRACK_PATH = "/api/v1/orders/track"
